pipeline {
  agent any

  parameters {
    string(
      name: 'IMAGE_TAG',
      defaultValue: '6',
      description: 'Enter Docker image tag to deploy'
    )
  }

  environment {
    HELM_RELEASE = "new-nginx"
    HELM_CHART   = "./deploy/Helm"
    NAMESPACE    = "jenkins"
  }

  stages {

    stage('Validate Parameter') {
      steps {
        script {
          if (!params.IMAGE_TAG?.trim()) {
            error("IMAGE_TAG parameter is required!")
          }
        }
      }
    }

    stage('Clone Repository') {
      steps {
        git branch: 'main',
            url: 'https://github.com/Sonali092/Newcdp.git'
      }
    }

    stage('Deploy using Helm') {
      steps {
        sh """
          kubectl create ns ${NAMESPACE} || true
          echo "Deploying image tag: ${params.IMAGE_TAG}"
          helm upgrade --install ${HELM_RELEASE} ${HELM_CHART} \
            --set image.tag=${params.IMAGE_TAG} -n ${NAMESPACE} --atomic --cleanup-on-fail
        """
      }
    }

    stage('Verify Deployment') {
      steps {
        sh """
           kubectl get pods -n ${NAMESPACE}
           kubectl get svc -n ${NAMESPACE}
           kubectl get ingress -n ${NAMESPACE}
           helm status ${HELM_RELEASE} -n ${NAMESPACE}
        """
      }
    }

  }
}